const theme = require("./theme.json")
const tailpress = require("@jeffreyvr/tailwindcss-tailpress")

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./*.php", "./**/*.php", "./resources/css/*.css", "./resources/js/*.js", "./safelist.txt"],
  safelist: [
    // 背景顏色
    "bg-red-50",
    "bg-orange-50",
    "bg-amber-50",
    "bg-yellow-50",
    "bg-lime-50",
    "bg-green-50",
    "bg-emerald-50",
    "bg-teal-50",
    "bg-cyan-50",
    "bg-sky-50",
    "bg-blue-50",
    "bg-indigo-50",
    "bg-violet-50",
    "bg-purple-50",
    "bg-fuchsia-50",
    "bg-pink-50",
    "bg-rose-50",

    "bg-red-100",
    "bg-orange-100",
    "bg-amber-100",
    "bg-yellow-100",
    "bg-lime-100",
    "bg-green-100",
    "bg-emerald-100",
    "bg-teal-100",
    "bg-cyan-100",
    "bg-sky-100",
    "bg-blue-100",
    "bg-indigo-100",
    "bg-violet-100",
    "bg-purple-100",
    "bg-fuchsia-100",
    "bg-pink-100",
    "bg-rose-100",

    "bg-red-200",
    "bg-orange-200",
    "bg-amber-200",
    "bg-yellow-200",
    "bg-lime-200",
    "bg-green-200",
    "bg-emerald-200",
    "bg-teal-200",
    "bg-cyan-200",
    "bg-sky-200",
    "bg-blue-200",
    "bg-indigo-200",
    "bg-violet-200",
    "bg-purple-200",
    "bg-fuchsia-200",
    "bg-pink-200",
    "bg-rose-200",

    // 添加 300 版本的背景顏色
    "bg-red-300",
    "bg-orange-300",
    "bg-amber-300",
    "bg-yellow-300",
    "bg-lime-300",
    "bg-green-300",
    "bg-emerald-300",
    "bg-teal-300",
    "bg-cyan-300",
    "bg-sky-300",
    "bg-blue-300",
    "bg-indigo-300",
    "bg-violet-300",
    "bg-purple-300",
    "bg-fuchsia-300",
    "bg-pink-300",
    "bg-rose-300",

    // 文本顏色
    "text-red-600",
    "text-orange-600",
    "text-amber-600",
    "text-yellow-600",
    "text-lime-600",
    "text-green-600",
    "text-emerald-600",
    "text-teal-600",
    "text-cyan-600",
    "text-sky-600",
    "text-blue-600",
    "text-indigo-600",
    "text-violet-600",
    "text-purple-600",
    "text-fuchsia-600",
    "text-pink-600",
    "text-rose-600",

    // 文本顏色
    "text-red-400",
    "text-orange-400",
    "text-amber-400",
    "text-yellow-400",
    "text-lime-400",
    "text-green-400",
    "text-emerald-400",
    "text-teal-400",
    "text-cyan-400",
    "text-sky-400",
    "text-blue-400",
    "text-indigo-400",
    "text-violet-400",
    "text-purple-400",
    "text-fuchsia-400",
    "text-pink-400",
    "text-rose-400",

    "text-red-800",
    "text-orange-800",
    "text-amber-800",
    "text-yellow-800",
    "text-lime-800",
    "text-green-800",
    "text-emerald-800",
    "text-teal-800",
    "text-cyan-800",
    "text-sky-800",
    "text-blue-800",
    "text-indigo-800",
    "text-violet-800",
    "text-purple-800",
    "text-fuchsia-800",
    "text-pink-800",
    "text-rose-800",

    "bg-opacity-10",
    "bg-opacity-20",

    "fill-red-200",
    "fill-orange-200",
    "fill-amber-200",
    "fill-yellow-200",
    "fill-lime-200",
    "fill-green-200",
    "fill-emerald-200",
    "fill-teal-200",
    "fill-cyan-200",
    "fill-sky-200",
    "fill-blue-200",
    "fill-indigo-200",
    "fill-violet-200",
    "fill-purple-200",
    "fill-fuchsia-200",
    "fill-pink-200",
  ],

  theme: {
    container: {
      padding: {
        DEFAULT: "1rem",
        sm: "2rem",
        lg: "0rem",
      },
    },
    extend: {
      colors: tailpress.colorMapper(tailpress.theme("settings.color.palette", theme)),
      fontSize: tailpress.fontSizeMapper(tailpress.theme("settings.typography.fontSizes", theme)),
    },
    screens: {
      xs: "480px",
      sm: "600px",
      md: "782px",
      lg: tailpress.theme("settings.layout.contentSize", theme),
      xl: tailpress.theme("settings.layout.wideSize", theme),
      "2xl": "1440px",
    },
    scrollbar: {
      DEFAULT: {
        track: "bg-gray-800",
        thumb: "bg-gray-600",
      },
      rounded: "rounded-md",
    },
  },
  plugins: [
    tailpress.tailwind,
    require("@tailwindcss/line-clamp"),
    require("tailwind-scrollbar"),
    function ({ addUtilities }) {
      addUtilities(
        {
          ".no-copy": {
            "user-select": "none",
          },
        },
        ["responsive", "hover"]
      )
    },
  ],
}
